<a href="https://colab.research.google.com/github/kosei-halfmoon4583/AppDConvert/blob/master/MyFisrtColab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [4]:
import torch.nn as nn

In [5]:
# 3ノード　→ 2ノードの全結合層（fully-connected layer)
fc = nn.Linear(3, 2)

In [6]:
fc

Linear(in_features=3, out_features=2, bias=True)

In [7]:
fc.weight

Parameter containing:
tensor([[ 0.4005,  0.4818, -0.5126],
        [-0.4608, -0.1940,  0.3100]], requires_grad=True)

In [8]:
fc.bias

Parameter containing:
tensor([0.3834, 0.5345], requires_grad=True)

In [9]:
# 乱数のシードを固定
torch.manual_seed(0)

In [10]:
fc = nn.Linear(3, 2)

In [11]:
fc.weight

Parameter containing:
tensor([[-0.0043,  0.3097, -0.4752],
        [-0.4249, -0.2224,  0.1548]], requires_grad=True)

In [12]:
fc.bias

Parameter containing:
tensor([-0.0114,  0.4578], requires_grad=True)

In [13]:
torch.__version__

'1.13.0+cu116'

*線形変換*
- データ型をテンソル型に変える

In [14]:
x = torch.tensor([[1., 2., 3.,]])

In [15]:
type(x), x.dtype

(torch.Tensor, torch.float32)

In [16]:
# 線形変換の計算
u = fc(x)

In [17]:
u

tensor([[-0.8219,  0.0526]], grad_fn=<AddmmBackward0>)

In [18]:
# 非線形変換の計算
import torch.nn.functional as F

In [19]:
# ReLU関数
h = F.relu(u)

In [20]:
h

tensor([[0.0000, 0.0526]], grad_fn=<ReluBackward0>)

In [21]:
# ReLU関数
# h = f(u) = max(0, u) [*0かuのどちらか大きい値を採用する]

In [22]:
# 目的関数
# 目標値
t = torch.tensor([[1.], [3.]])

In [23]:
# 予測値
y = torch.tensor([[2.], [4.]])

In [24]:
# 平均二乗誤差の算出
F.mse_loss(y, t)

tensor(1.)